#! /usr/bin/env bash

MAIN_CONFIGURATION_PATH="$HOME/.config/viver"
SHIMS_PATH="${MAIN_CONFIGURATION_PATH}/bin"
SETUPS_PATH="${MAIN_CONFIGURATION_PATH}/setups"

VIM_BIN_PATH="/usr/bin/vim"
NVIM_BIN_PATH="/usr/bin/nvim"

DEFAULT_VIM_RUNTIME_PATHS=(
  "\\\$VIM/vimfiles"
  "\\\$VIMRUNTIME"
  "\\\$VIM/vimfiles/after"
)

DEFAULT_NVIM_RUNTIME_PATHS=(
  "/usr/local/share/nvim/site"
  "\\\$VIM/site"
  "\\\$VIMRUNTIME"
  "/usr/lib/nvim"
  "\\\$VIM/site/after"
  "/usr/local/share/nvim/site/after"
  "/etc/xdg/nvim/after"
)

function main() {
  editor_options=$1
  declare -A current_config

  print_about
  initialize_main
  main_menu "${editor_options}"
}

function print_about() {
  cat <<-EOF

Viver is a simple configuratoin manager for Vim and Neovim written in Bash.
See the usage examples here: https://github.com/zinovyev/viver

EOF
}

function initialize_main() {
  mkdir -p  $SHIMS_PATH
  mkdir -p  $SETUPS_PATH
}
function main_menu() {
  editor_options=$1

  while :
  do
    print_main_menu

    user_input="$(get_user_input "Please choose an option: ")"
    if [[ "${user_input}" == "" ]]; then continue; fi

    case $user_input in 
      "E"|"e")
        action_execute "${editor_options}"
        ;;
      "N"|"n")
        action_new
        ;;
      "D"|"d"|"R"|"r")
        action_remove
        ;;
      "L"|"l")
        action_list
        ;;
      "T"|"t")
        action_debug
        ;;
      "Q"|"q")
        exit 0
        ;;

      *) 
        echo "Unknown option: \"${user_input}\"" 
        ;; 
    esac
  done
}

function print_main_menu() {
  cat <<-EOF
[E]xecute      Execute the editor command with selected configuration
[N]ew          Create a new configuration
[R]emove       Remove existing configuration
[L]ist         List available configurations
[T]est         Print out what the execute command is going to execute for a particular configuration
[Q]uit         Quit

EOF
}
function action_execute() {
  editor_options=$1

  echo "Execute the editor command"

  while :
  do
    list_configurations

    config_name="$(get_user_input "Please choose a name to execute (or [Q] to go back): ")"
    if [[ "${config_name}" == "" ]]; then continue; fi
    if [[ "${config_name}" == "Q" ]] || [[ "${config_name}" == "q" ]]; then return; fi

    parse_config "${config_name}"

    if [[ ! "${current_config[name]}" == "" ]]; then
      print_config 

      cmd="$(build_command "${editor_options}")"

      bash -c "${cmd}"

      break
    fi
  done
}
function action_list() {
  echo -e "\nKnown configurations:\n"

  list_configurations

  echo
  get_user_input
}
function action_new() {
  select_editor_menu

  config_name=
  config_path=
  while :
  do
    config_name="$(get_user_input "Please set the config name: ")"
    if [[ "${config_name}" == "" ]]; then continue; fi

    config_path="${SETUPS_PATH}/${config_name}"

    if [[ -e "$config_path" ]]; then
      echo "Path \"${config_path}\" already exists. Try another name"
      continue
    fi

    break
  done

  ensure_file_exists "${config_path}/.editor" $editor_name
  ensure_file_exists "${config_path}/init.vim"
  ensure_file_exists "${config_path}/.viminfo"

  parse_config "${config_name}"
  cmd="$(build_command "\$@")"

  echo $cmd > "${current_config[shim_path]}"
  chmod +x "${current_config[shim_path]}"
}

function select_editor_menu() {
  print_select_editor_menu

  editor_name=
  while :
  do
    user_input="$(get_user_input "Please choose an editor: ")"
    if [[ "${user_input}" == "" ]]; then continue; fi

    case $user_input in 
      "V"|"v")
        editor_name="vim"
        break
        ;;
      "N"|"n")
        editor_name="nvim"
        break
        ;;
      "Q"|"q")
        return
        ;;

      *) 
        echo "Unknown editor: \"${user_input}\"" 
        ;; 
    esac
  done
}

function print_select_editor_menu() {
  cat <<-EOF

[V]im          ${VIM_BIN_PATH}
[N]eovim       ${NVIM_BIN_PATH}
[Q]uit         To go back

EOF
}
function action_remove() {
  echo "Remove configuration"

  while :
  do
    list_configurations
    config_name="$(get_user_input "Please choose a name to remove (or [Q] to go back): ")"
    if [[ "${config_name}" == "" ]]; then continue; fi
    if [[ "${config_name}" == "Q" ]] || [[ "${config_name}" == "q" ]]; then return; fi

    parse_config "${config_name}"

    if [[ ! "${current_config[name]}" == "" ]]; then
      remove_configuration_menu

      break
    fi
  done
}

function remove_configuration_menu() {
  print_configuration_menu

  editor_name=
  while :
  do
    user_input="$(get_user_input "Are you sure you want to remove \"${current_config[name]}\": ")"
    if [[ "${user_input}" == "" ]]; then continue; fi

    case $user_input in 
      "Y"|"y")
        echo "Removing \"${current_config[name]}\"...\n"
        rm -rf "${current_config[full_path]}"
        rm "${current_config[shim_path]}"

        break
        ;;
      "N"|"n")
        return
        ;;

      *) 
        echo "Unknown command: \"${user_input}\"" 
        ;; 
    esac
  done
}

function print_configuration_menu() {
  cat <<-EOF

[Y]es          To proceed
[N]o           To cancel

EOF
}
function action_debug() {
  editor_options=$1

  echo "Debug the editor command"

  while :
  do
    list_configurations

    config_name="$(get_user_input "Please choose a name to execute (or [Q] to go back): ")"
    if [[ "${config_name}" == "" ]]; then continue; fi
    if [[ "${config_name}" == "Q" ]] || [[ "${config_name}" == "q" ]]; then return; fi

    parse_config "${config_name}"

    if [[ ! "${current_config[name]}" == "" ]]; then
      print_config 

      cmd="$(build_command "${editor_options}")"

      echo $cmd
      echo

      break
    fi
  done
}

function list_configurations() {
  configurations=($(find $SETUPS_PATH -mindepth 1 -maxdepth 1 -type d))

  for idx in ${!configurations[@]}; do
    config_name=$(basename "${configurations[$idx]}")
    parse_config "${config_name}"
    print_config
  done
}

function print_config() {
  echo
  for i in "${!current_config[@]}"
  do
    echo "${i}: ${current_config[$i]}"
  done
  echo
}

function parse_config() {
  config_name=$1
  config_path="${SETUPS_PATH}/${config_name}"
  editor_name=$(cat "${config_path}/.editor")

  current_config[full_path]=$config_path
  current_config[name]=$(basename $config_path)
  current_config[editor]=$editor_name
  current_config[init_path]="${config_path}/init.vim"
  current_config[viminfo_path]="${config_path}/.viminfofile"
  current_config[runtime_path]=$(build_runtime_path $editor_name $config_path)
  current_config[bin_path]=$(choose_editor_bin_path $editor_name)
  current_config[shim_path]="${SHIMS_PATH}/${config_name}"
}

function build_command() {
  editor_options=$1

  cmd="${current_config[bin_path]} ${editor_options}"
  ensure_file_exists "${current_config[init_path]}"
  runtime_path_cmd="--cmd \"set nocp\" "
  runtime_path_cmd+="--cmd \"set runtimepath=${current_config[runtime_path]}\" "
  runtime_path_cmd+="--cmd \"set packpath=${current_config[runtime_path]}\" "
  runtime_path_cmd+="--cmd \"set viminfofile=${current_config[viminfo_path]}\""

  echo "export MYVIMHOME=${current_config[full_path]} export MYVIMRC=${current_config[init_path]} ; " \
    "${cmd} -u ${current_config[init_path]} ${runtime_path_cmd}"
}

function build_runtime_path() {
  editor_name=$1
  config_path=$2

  default_runtime_paths=""
  case $editor_name in 
    "vim")
      default_runtime_paths=$(IFS=,; printf %s "${DEFAULT_VIM_RUNTIME_PATHS[*]}")
      ;;
    "nvim")
      default_runtime_paths=$(IFS=,; printf %s "${DEFAULT_NVIM_RUNTIME_PATHS[*]}")
      ;;
    *) raise_error "Invalid editor name \"${editor_name}\"" ;; 
  esac


  echo "${config_path},${default_runtime_paths},${config_path}/after"
}

function choose_editor_bin_path() {
  editor_name=$1

  case $editor_name in 
    "vim")
      editor_bin_path="${VIM_BIN_PATH}"
      ;;
    "nvim")
      editor_bin_path="${NVIM_BIN_PATH}"
      ;;
    *) raise_error "Invalid "${editor_bin_path}" editor name \"${1}\"" ;; 
  esac

  echo "$editor_bin_path"
}
function ensure_file_exists() {
  if [[ "$1" == "" ]]; then raise_error "File path is not defined!"; fi
  if [ ! -e "$1" ]; then
    install -D <(echo $2) $1
  fi
}

function raise_error() {
  echo $1

  kill -15 "$$"
}

function get_user_input() {
  prompt=$1

  read -p "${prompt}" input

  echo $input
}

main $@
